apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustomizegoat
  name: goatlb
  namespace: kustomizegoat
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kustomizegoat
  type: LoadBalancer